source "http://rubygems.org"

gem "rack", "~> 1.3"
gem "tilt", "~> 1.3"
gem "i18n", "~> 0.6"
gem "sass", "~> 3.1"
gem "activesupport", ">= 3.1"
gem "sprockets", "~> 2.0"
gem "erubis"
gem "coffee-script", "2.2.0"
gem "tipsy", "0.1.3"

# Thin or mongrel are recommended over Webrick
# gem "thin"

# Uglifier is recommended for javascript compression. If unavailable, Google's online 
# closure compiler will be used.
#gem 'uglifier'

# Compass is automatically detected and configured if available
gem "compass", "~> 0.11"